name: Generate static site and deploy it to GitHub Pages

on:
    push:
        branches: ['master']

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Prepare environment
              run: corepack enable pnpm
              
            - name: Install dependencies
              run: pnpm i

            - name: Generate static site
              run: pnpm generate

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
